<a href="https://colab.research.google.com/github/crdsteixeira/OR_project/blob/main/Scheduling_Aircraft_Landings_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Download the library

In [2]:
# !pip install docplex
# !pip install cplex

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 640.2/640.2 KB 32.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for docplex: filename=docplex-2.24.232-py3-none-any.whl size=682306 sha256=dd437d0f0bb7d2c6b32755ee90517d2a0a928cadc7fe6481f7581475a63ee510
  Stored in directory: /root/.cache/pip/wheels/cd/84/5d/b9c307d9cf361c49d41ddea36761e226bba3afdfd038673dcd
Successfully built docplex
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 MB 21.0 MB/s eta 0:00:00


In [28]:
from docplex.cp.model import *
import numpy as np

# Info

The format of these data files is:
number of planes (p), freeze time
for each plane i (i=1,...,p):
   - appearance time, 
   - earliest landing time, 
   - target landing time,
   - latest landing time, 
   - penalty cost per unit of time for landing before target, 
   - penalty cost per unit of time for landing after target

for each plane j (j=1,...p): separation time required after 
                                i lands before j can land


### Sigle runway definitions and variables

![image.png](https://github.com/crdsteixeira/OR_project/blob/main/Images/single_run.png?raw=1)


### Multirunway defintions and variables 

![image.png](https://github.com/crdsteixeira/OR_project/blob/main/Images/multi_run.png?raw=1)

## Get data

In [37]:
def read_datafiles(file):
    with open(file, 'r') as data:
        data_lines = data.readlines()
        number_planes = int(data_lines[0].split()[0])
        freeze_time =  int(data_lines[0].split()[1])
        mixed_data = [line.split() for line in data_lines[1:] if not line.isspace()]
        mixed_data = [[(float(j)) for j in i] for i in mixed_data]
        
        flight_details = np.empty([0,6],dtype=float)
        separation_time = np.empty([0,number_planes],dtype=float)
        
        flag = 0
       
        for element in mixed_data:
            if flag == 0: # flight details
                flight_details = np.vstack([flight_details, np.array(element)])
                flag = 1
                element_final = []
            else:  # separation_times
                element_final.extend(element)
                if len(element_final) == number_planes:
                    separation_time = np.vstack([separation_time, np.array(element_final)])
                    flag = 0
                
#         print(f" number planes: {number_planes}")
#         print(f" freeze time: {freeze_time}")
#         print(f" mixed data: {mixed_data}")
#         print(f" flight details: {flight_details}")
#         print(f" separation time: {separation_time}")
    
    return number_planes, freeze_time, flight_details, separation_time


In [5]:
read_datafiles("./airland1.txt")

 number planes: 10
 freeze time: 10
 mixed data: [[54.0, 129.0, 155.0, 559.0, 10.0, 10.0], [99999.0, 3.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0], [15.0, 15.0], [120.0, 195.0, 258.0, 744.0, 10.0, 10.0], [3.0, 99999.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0], [15.0, 15.0], [14.0, 89.0, 98.0, 510.0, 30.0, 30.0], [15.0, 15.0, 99999.0, 8.0, 8.0, 8.0, 8.0, 8.0], [8.0, 8.0], [21.0, 96.0, 106.0, 521.0, 30.0, 30.0], [15.0, 15.0, 8.0, 99999.0, 8.0, 8.0, 8.0, 8.0], [8.0, 8.0], [35.0, 110.0, 123.0, 555.0, 30.0, 30.0], [15.0, 15.0, 8.0, 8.0, 99999.0, 8.0, 8.0, 8.0], [8.0, 8.0], [45.0, 120.0, 135.0, 576.0, 30.0, 30.0], [15.0, 15.0, 8.0, 8.0, 8.0, 99999.0, 8.0, 8.0], [8.0, 8.0], [49.0, 124.0, 138.0, 577.0, 30.0, 30.0], [15.0, 15.0, 8.0, 8.0, 8.0, 8.0, 99999.0, 8.0], [8.0, 8.0], [51.0, 126.0, 140.0, 573.0, 30.0, 30.0], [15.0, 15.0, 8.0, 8.0, 8.0, 8.0, 8.0, 99999.0], [8.0, 8.0], [60.0, 135.0, 150.0, 591.0, 30.0, 30.0], [15.0, 15.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0], [99999.0, 8.0], [85.0, 160.0, 180.0, 657.0, 30.

(10, 10, array([[ 54., 129., 155., 559.,  10.,  10.],
        [120., 195., 258., 744.,  10.,  10.],
        [ 14.,  89.,  98., 510.,  30.,  30.],
        [ 21.,  96., 106., 521.,  30.,  30.],
        [ 35., 110., 123., 555.,  30.,  30.],
        [ 45., 120., 135., 576.,  30.,  30.],
        [ 49., 124., 138., 577.,  30.,  30.],
        [ 51., 126., 140., 573.,  30.,  30.],
        [ 60., 135., 150., 591.,  30.,  30.],
        [ 85., 160., 180., 657.,  30.,  30.]]), array([[9.9999e+04, 3.0000e+00, 1.5000e+01, 1.5000e+01, 1.5000e+01,
         1.5000e+01, 1.5000e+01, 1.5000e+01, 1.5000e+01, 1.5000e+01],
        [3.0000e+00, 9.9999e+04, 1.5000e+01, 1.5000e+01, 1.5000e+01,
         1.5000e+01, 1.5000e+01, 1.5000e+01, 1.5000e+01, 1.5000e+01],
        [1.5000e+01, 1.5000e+01, 9.9999e+04, 8.0000e+00, 8.0000e+00,
         8.0000e+00, 8.0000e+00, 8.0000e+00, 8.0000e+00, 8.0000e+00],
        [1.5000e+01, 1.5000e+01, 8.0000e+00, 9.9999e+04, 8.0000e+00,
         8.0000e+00, 8.0000e+00, 8.0000e+00, 

# The MIP model

In [58]:
def MIP_model(file_name,R):
    from docplex.mp.model import Model
    mdl = Model("Scheduling Aircraft Landing - Multi Runaway Static Case")
    
    P, freeze_time, flight_details, separation_time = read_datafiles(file_name)
    
    # The first column relates to the actual appearence time of the plane so will not be taken into account for our decision variables

    E = flight_details[:,1]  #earliest landing time,
    T = flight_details[:,2]  #target landing time,
    L = flight_details[:,3]  #latest landing time,
    g = flight_details[:,4]  #penalty cost per unit of time for landing before target,
    h = flight_details[:,5]  #penalty cost per unit of time for landing after target
    range_LT = max(flight_details[:,3]) - min(flight_details[:,1]) #landing range time

    s = separation_time      # here we consider separation time between planes that land in different runways, fundamentally their value is the same as the separation time matrix but in constraints it should be multiplied by the binary variable that says if the planes land in the same runway or not

    ij = [(i,j) for i in np.arange(P) for j in np.arange(P)] # indexes for plane i and j landing in the same runway
    ir = [(i, r) for i in np.arange(P) for r in np.arange(R)] # indexes for plane i landing in runway r

    # Creating the time spaces
    W = []
    V = []
    U = []
    for i in range(P):
        for j in range(P):
            if i != j:
                min_range_i, min_range_j, max_range_i, max_range_j = E[i], E[j], L[i], L[j]
                land_range_i = [min_range_i, max_range_i]
                land_range_j = [min_range_j, max_range_j]

                overlap = max(0, min(land_range_i[1], land_range_j[1]) - max(land_range_i[0], land_range_j[0])) #Check if landing intervals overlap

          # To confirm if the separation time window is safe we should see if latest landing time of plane i plus the separation time  
          # between plane i and j is lower and then the earliest landing time for plane j

          # This way we are also confirming that i lands before j

                if (overlap == 0) and ((L[i] + separation_time[i,j]) < E[j]): # confirm that the windows don't intersept and separation time is big enough
                  W.append((i,j))
                else:
                    if (L[i] < E[j]): # windows intersept but we know that i lands before j
                        V.append((i,j))
                    else: 
                        U.append((i,j)) # we don't know the order in which one lands
            else: 
                continue
    

    # Defining decision variables

    alpha   = mdl.continuous_var_dict(np.arange(P),lb=0,ub=mdl.infinity, name="alpha") # how soon a plane lands before target time
    beta    = mdl.continuous_var_dict(np.arange(P),lb=0,ub=mdl.infinity, name="beta") # how soon a plane lands after target time
    x       = mdl.continuous_var_dict(np.arange(P),lb=0,ub=mdl.infinity, name="x") # landing time for a plane
    sigma   = mdl.binary_var_dict(ij,lb=0,ub=1, name="sigma") # binary variable: 1 if plane i lands before plane j, 0 elsewhere
    y       = mdl.binary_var_dict(ir,lb=0,ub=1, name="y") # 1 if plane i lands on runway  r , 0 otherwise
    z       = mdl.binary_var_dict(ij,lb=0,ub=1, name="z") # 1 if planes i and  j land on the same runway, 0 otherwise



    # Adding constraints
    
    mdl.add_constraints(x[i]>=E[i] for i in np.arange(P)) # Const 1 - Landing time of plane i must be later than the earliest landing time
    mdl.add_constraints(x[i]<=L[i] for i in np.arange(P)) # Const 1 - Landing time of plane i must be earlier than the before latest landing time
    mdl.add_constraints(sigma[i,j]+sigma[j,i]==1 for i in np.arange(P) for j in np.arange(P) if j!=i)  # Const 2 - Plain i must land before plain j or plain j before plain i
    mdl.add_constraints(alpha[i]>=T[i]-x[i] for i in np.arange(P)) # Const 14 - How soon plane i lands before T[i] must be larger than T[i] - x[i]
    mdl.add_constraints(alpha[i]<=T[i]-E[i] for i in np.arange(P)) # Const 15 - How soon plane i lands before T[i] must be smaller than T[i] - E[i]
    mdl.add_constraints(alpha[i]>= 0 for i in np.arange(P)) # Const 15 - How soon plane i lands before T[i] must be at least zero
    mdl.add_constraints(beta[i]>=x[i]-T[i] for i in np.arange(P))  # Const 16 - How soon plane i lands after T[i] must be larger than x[i] - T[i]
    mdl.add_constraints(beta[i]<=L[i]-T[i] for i in np.arange(P))  # Const 17 - How soon plane i lands after T[i] must be smaller than L[i] - T[i]
    mdl.add_constraints(beta[i]>= 0 for i in np.arange(P))  # Const 17 - How soon plane i lands after T[i] must be at least zero
    mdl.add_constraints(x[i]==T[i]-alpha[i]+beta[i] for i in np.arange(P))  # Const 18 - Landing time is equal to target time minus arriving early or plus arriving late
   
    mdl.add_constraints(mdl.sum(y[i,r] for r in np.arange(R))==1 for i in np.arange(P))     # Const 28 - Plane i can only land in 1 runaway
    mdl.add_constraints(z[i,j]==z[j,i] for i in np.arange(P) for j in np.arange(P) if j>i)  # Const 29 - Symetry constraint: If plane i lands in the same runaway as plane j, plane j lands in the same runaway as plane i
    mdl.add_constraints(z[i,j]>=y[i,r]+y[j,r]-1 for r in np.arange(R) for j in np.arange(P) for i in np.arange(P) if j>i) # Const 30 - If there is any runaway r for which y[i,r]=y[j,r]=1 then z[i,j]=1. If z[i,j]=0 then the planes i and j cannot land on the same runaway 
    
    # Const 6 - If plane i lands before j we know that they belong in subspace W or V 
#     for i in range(P):
#         for j in range(P):
#         if ((i,j) in V) or ((i,j) in W):
    mdl.add_constraints(sigma[i,j] == 1 for i in np.arange(P) for j in np.arange(P) if ((i,j) in V) or ((i,j) in W))
          
#     # Const 12 - Separation time between plane i and plane j must be respected
#     for i in range(P):
#         for j in range(P):
#             if (i,j) in U:
#     print(separation_time[i,j] * sigma[j,i])
#     mdl.add_constraints(x[j] >= (x[i] + (separation_time[i,j]*sigma[j,i]) - ((L[i] - E[j])*sigma[i,j])) for i in np.arange(P) for j in np.arange(P) if (i,j) in U and i != j)  

#     # Const 31 - Landing times should respect separation times considering if they land in the same runway or not in subspace V

    mdl.add_constraints(x[j] >= (x[i] + separation_time[i,j]*z[i,j] + s[i,j]*(1-z[i,j])) for i in np.arange(P) for j in np.arange(P) if (i,j) in V )

    # Const 33 - Landing times should respect separation times considering if they land in the same runway or not in subspace U
    mdl.add_constraints(x[j] >= (x[i] + separation_time[i,j]*z[i,j] + s[i,j]*(1-z[i,j] - (L[i] + max(separation_time[i,j], s[i,j] - E[j])*sigma[i,j]))) for i in np.arange(P) for j in np.arange(P) if (i,j) in U)


    cost_function = mdl.sum(beta[i] * h[i] + alpha[i] * g[i] for i in np.arange(P))

    mdl.minimize(cost_function)
    
    mdl.print_information()

    msol = mdl.solve()
    assert msol is not None, "model can't solve"

    return mdl

In [59]:
file_name = "./Data/airland6.txt"
R = 2

mdl_ = MIP_model(file_name, R)
mdl_.report()
mdl_.print_solution()

Model: Scheduling Aircraft Landing - Multi Runaway Static Case
 - number of variables: 1950
   - binary=1860, integer=0, continuous=90
 - number of constraints: 3373
   - linear=3373
 - parameters: defaults
 - objective: minimize
 - problem type is: MILP
* model Scheduling Aircraft Landing - Multi Runaway Static Case solved with objective = 963.000
objective: 963.000
status: OPTIMAL_SOLUTION(2)
  beta_1=17.000
  beta_2=48.000
  beta_3=188.000
  beta_4=24.000
  beta_22=43.000
  x_1=96.000
  x_2=192.000
  x_3=392.000
  x_4=288.000
  x_5=320.000
  x_6=528.000
  x_7=635.000
  x_8=730.000
  x_9=766.000
  x_10=790.000
  x_11=920.000
  x_12=1046.000
  x_13=1106.000
  x_14=1136.000
  x_15=1166.000
  x_16=1233.000
  x_17=1642.000
  x_18=1715.000
  x_19=1770.000
  x_20=2074.000
  x_21=2168.000
  x_22=2302.000
  x_23=2427.000
  x_24=2481.000
  x_25=2679.000
  x_26=2883.000
  x_27=2982.000
  x_28=3046.000
  x_29=3091.000
  sigma_0_1=1
  sigma_0_2=1
  sigma_0_3=1
  sigma_0_4=1
  sigma_0_5=1
  sigma

## The CP model

In [ ]:
def read_datafiles_cp(file):
    with open(file, 'r') as data:
        data_lines = data.readlines()
        number_planes = int(data_lines[0].split()[0])
        freeze_time =  int(data_lines[0].split()[1])
        mixed_data = [line.split() for line in data_lines[1:] if not line.isspace()]
        mixed_data = [[(float(j)) for j in i] for i in mixed_data]
        
        flight_details = np.empty([0,6],dtype=float)
        separation_time = np.empty([0,number_planes],dtype=float)
        
        flag = 0
       
        for element in mixed_data:
            if flag == 0: # flight details
                flight_details = np.vstack([flight_details, np.array(element)])
                flag = 1
                element_final = []
            else:  # separation_times
                element_final.extend(element)
                if len(element_final) == number_planes:
                    separation_time = np.vstack([separation_time, np.array(element_final)])
                    flag = 0

        minimum = min(flight_details[:,1])
        maximum = max(flight_details[:,3])
        num_periods = int(minimum % 10)
        int_size = (maximum-minimum)//num_periods #CT: Adicionei max-min
        period_constraints = []

        x = (0,0)
        lst = list(x)
        for i in range(num_periods-1): #CT: Adicionei -1 
            lst[0], lst[1] = int_size * i, int_size * (i+1)
            x = tuple(lst)
            period_constraints.append(x)

                
        print(f" number planes: {number_planes}")
        print(f" num_periods: {num_periods}")
        print(f" flight details: {flight_details}")
        print(f" period_constraints: {period_constraints}")
    
    return number_planes, num_periods, flight_details, separation_time, period_constraints #CT:added separation time

In [ ]:
read_datafiles_cp("./Data/airland1.txt")

 number planes: 10
 num_periods: 9
 flight details: [[ 54. 129. 155. 559.  10.  10.]
 [120. 195. 258. 744.  10.  10.]
 [ 14.  89.  98. 510.  30.  30.]
 [ 21.  96. 106. 521.  30.  30.]
 [ 35. 110. 123. 555.  30.  30.]
 [ 45. 120. 135. 576.  30.  30.]
 [ 49. 124. 138. 577.  30.  30.]
 [ 51. 126. 140. 573.  30.  30.]
 [ 60. 135. 150. 591.  30.  30.]
 [ 85. 160. 180. 657.  30.  30.]]
 period_constraints: [(0.0, 72.0), (72.0, 144.0), (144.0, 216.0), (216.0, 288.0), (288.0, 360.0), (360.0, 432.0), (432.0, 504.0), (504.0, 576.0)]


(10,
 9,
 array([[ 54., 129., 155., 559.,  10.,  10.],
        [120., 195., 258., 744.,  10.,  10.],
        [ 14.,  89.,  98., 510.,  30.,  30.],
        [ 21.,  96., 106., 521.,  30.,  30.],
        [ 35., 110., 123., 555.,  30.,  30.],
        [ 45., 120., 135., 576.,  30.,  30.],
        [ 49., 124., 138., 577.,  30.,  30.],
        [ 51., 126., 140., 573.,  30.,  30.],
        [ 60., 135., 150., 591.,  30.,  30.],
        [ 85., 160., 180., 657.,  30.,  30.]]),
 array([[9.9999e+04, 3.0000e+00, 1.5000e+01, 1.5000e+01, 1.5000e+01,
         1.5000e+01, 1.5000e+01, 1.5000e+01, 1.5000e+01, 1.5000e+01],
        [3.0000e+00, 9.9999e+04, 1.5000e+01, 1.5000e+01, 1.5000e+01,
         1.5000e+01, 1.5000e+01, 1.5000e+01, 1.5000e+01, 1.5000e+01],
        [1.5000e+01, 1.5000e+01, 9.9999e+04, 8.0000e+00, 8.0000e+00,
         8.0000e+00, 8.0000e+00, 8.0000e+00, 8.0000e+00, 8.0000e+00],
        [1.5000e+01, 1.5000e+01, 8.0000e+00, 9.9999e+04, 8.0000e+00,
         8.0000e+00, 8.0000e+00, 8.0000e+00

In [ ]:
def CP_model(file_name,R):
    num_aircrafts, num_periods, aircraft_data, separation_time, period_constraints = read_datafiles_cp(file_name) #CT:added separation_time
    
    def discretize_time(time):    # CT: added
        for i in period_constraints:
            if time >= i[0] and time <= i[1]:
                return period_constraints.index(i)
         
    E = aircraft_data[:,1]  #earliest landing time,
    T = aircraft_data[:,2]  #target landing time,
    L = aircraft_data[:,3]  #latest landing time,
    g = aircraft_data[:,4]  #penalty cost per unit of time for landing before target,
    h = aircraft_data[:,5]  #penalty cost per unit of time for landing after target
    range_LT = max(aircraft_data[:,3]) - min(aircraft_data[:,1]) #landing range time
    ij = [(i,j) for i in np.arange(num_aircrafts) for j in np.arange(num_aircrafts)]
    ir = [(i, r) for i in np.arange(num_aircrafts) for r in np.arange(R)]

    from docplex.cp.model import CpoModel

    # Create the model
    model = CpoModel("aircraft_landing_problem")

    # Create variables
    
    n_planes = num_aircrafts   # CT: added
    planes = model.integer_var_list(size=n_planes, min=1, max=n_planes, name="Planes") # CT: added
    model.add(model.all_diff(planes)) # CT: added
    
    x = model.binary_var_list(num_aircrafts, "x") # 1 if aircraft i lands in period t, 0 otherwise

    # faltam variaveis aqui ainda

    # Const 1 - An aircraft must land in exactly one period
    for i in range(num_aircrafts):
        model.add(model.sum(x[i, t] for t in range(num_periods)) == 1)

    # Const 2 - The minimum value of target landing time must be in the first time interval
    for i in range(num_aircrafts):
        model.add((T[i] >= min(period_constraints[0])) and (T[i] <= max(period_constraints[0])))


    # Const 3 - The maximum value of target landing time must be in the last time interval
    for i in range(num_aircrafts):
        model.add((T[i] >= min(period_constraints[-1])) and (T[i] <= max(period_constraints[-1])))

  #############################################--------------############################







In [ ]:
file_name = "./Data/airland1.txt"
R = 2
CP_model(file_name, R)

 number planes: 10
 num_periods: 9
 flight details: [[ 54. 129. 155. 559.  10.  10.]
 [120. 195. 258. 744.  10.  10.]
 [ 14.  89.  98. 510.  30.  30.]
 [ 21.  96. 106. 521.  30.  30.]
 [ 35. 110. 123. 555.  30.  30.]
 [ 45. 120. 135. 576.  30.  30.]
 [ 49. 124. 138. 577.  30.  30.]
 [ 51. 126. 140. 573.  30.  30.]
 [ 60. 135. 150. 591.  30.  30.]
 [ 85. 160. 180. 657.  30.  30.]]
 period_constraints: [(0.0, 72.0), (72.0, 144.0), (144.0, 216.0), (216.0, 288.0), (288.0, 360.0), (360.0, 432.0), (432.0, 504.0), (504.0, 576.0)]
6


NameError: name 'n_plannes' is not defined